FROM central-mirror.services.mts.ru/dotnet/sdk:8.0 AS build

RUN echo "deb http://nexus.services.mts.ru/repository/debian-bookworm-proxy bookworm main" > /etc/apt/sources.list \
    && echo "deb http://nexus.services.mts.ru/repository/debian-security bookworm-security main" >> /etc/apt/sources.list \
    && echo "deb http://nexus.services.mts.ru/repository/debian-bookworm-proxy bookworm-updates main" >> /etc/apt/sources.list

RUN apt-get update --allow-insecure-repositories \    
    && apt-get install -y --no-install-recommends ca-certificates curl gettext-base libicu72=72.1-3+deb12u1    

WORKDIR /usr/local/share/ca-certificates
RUN curl -OOOO -XGET https://pki.mts.ru/https://gitlab.services.mts.ru/salsa/mnp-hub/informing/informing-data.git \
    && update-ca-certificates --fresh \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* 

WORKDIR /src
COPY ["NuGet.config", "./NuGet.config"]
COPY ["src/Informing.Data.Domain/Informing.Data.Domain.csproj", "Informing.Data.Domain/"]
COPY ["src/Informing.Data.Infrastructure/Informing.Data.Infrastructure.csproj", "Informing.Data.Infrastructure/"]
COPY ["src/Informing.Data.Worker/Informing.Data.Worker.csproj", "Informing.Data.Worker/"]

RUN dotnet restore "Informing.Data.Worker/Informing.Data.Worker.csproj"
COPY src/. .
RUN dotnet build "Informing.Data.Worker/Informing.Data.Worker.csproj" -c Release --no-restore -o /app/build

WORKDIR "/src/Informing.Data.Worker"
FROM build AS publish
RUN dotnet publish "Informing.Data.Worker.csproj" --no-restore -c Release -o /app/publish /p:UseAppHost=false

FROM central-mirror.services.mts.ru/dotnet/runtime:8.0 AS final

RUN addgroup --system nonroot \
    && adduser --system --ingroup nonroot nonroot
USER nonroot

WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Informing.Data.Worker.dll"]